#Database
POSTGRESQL_USERNAME: utin
POSTGRESQL_PASSWORD: Pass123
POSTGRESQL_HOST: 192.168.0.103
POSTGRESQL_PORT: 5432
POSTGRESQL_DATABASE: oj

#server
CONTAINER_PORT: 8085
ACTIVE_PROFILE: dev

#Email
EMAIL_HOST: smtp.gmail.com
EMAIL_PORT: 587
EMAIL_ID: abdulalimdhuronto24@gmail.com
EMAIL_PASSWORD: iofd lhfx bdbu jske
VERIFY_EMAIL_HOST: http://localhost:8080

JWT_EXPIRATION: 432_000_000 #432_000_000 S -> 5 days
JWT_SECRET: ${SECRET}
