#Database
POSTGRESQL_USERNAME: utin
POSTGRESQL_PASSWORD: Pass123
POSTGRESQL_HOST: 192.168.0.101
POSTGRESQL_PORT: 5432
POSTGRESQL_DATABASE: db

#server
CONTAINER_PORT: 8085
ACTIVE_PROFILE: prod

#Email
EMAIL_HOST: smtp.gmail.com
EMAIL_PORT: 587
EMAIL_ID: blackhunters711@gmail.com
EMAIL_PASSWORD: 2546742752
VERIFY_EMAIL_HOST: http://localhost:8085

JWT_EXPIRATION: 432_000_000 #432_000_000 S -> 5 days
JWT_SECRET: ${SECRET}